### ISSUE TITLE
グラフを論文に使えるくらい良い感じにしたい

### ISSUE THREAD

**Issue by kyawawa** [kindsenior/log_plotter#43]
pyqtgraphでやることではないのかもしれませんが立てます．

考えられる事柄は，
- [x] 1. フォント，フォントサイズを指定する
- [x] 2. グラフのサイズを指定できるようにする
- [x] 3. 軸の色を灰色から黒にし，補助線を点線にする
- [x] 4. グラフの系列(?)の背景を薄灰色から白塗りつぶしにする
- [x] 5. グラフの色を見やすくする

などでしょうか．
@rkoyama1623 がやっていると噂のmatplotlibライクな出力するのも手かもしれませんが，どんな感じでしょう？

5.について，plot_method.pyで指定しているcolor_listをgnuplot5.0のデフォルトのものにしてみたら，そこそこ見やすくなった気がします．

**Comment by kindsenior** [comment]
そうですね
僕は全体的に賛成です

作戦として2つあると思っていて
a. @rkoyama1623  がやっているようにmatplotlibモードを追加する(matplotlibライクというよりはmatplotlibを使っている？)
b. pyqtgraphの設定を変える・変えられるようにする
で個人的にはaはメンテナンスが大変そうなのでbでいいような気がしてます

bの場合は
3,4,5はデフォルト値を変えてしまうだけでも目下十分な気がしていて，多分gnuplotとかmatplotlibとかと同じ感じにすればいいと思ってます
1,2はGUIが必要になのでどのように指定するのがいいか要検討ですね

皆さんご意見願います

**Comment by rkoyama1623-jsk** [comment]
残りは，
1. フォント，フォントサイズを指定する
- guiで変える
- yamlでも設定できると良い
2. グラフのサイズを指定できるようにする
- yamlでも設定できると良い

2のyamlでの設定の優先度が高そう．
横一列が同一サイズで良ければ，
```yaml
- title: watt
  legends:
    - { key: watt, id: [0-5] }
  height: 400
  width: 500
```
のように書くと，横一列が400x500になるというのが目標かなと思っています．
yamlの仕様を先に決めておきたいところです．
将来的に，複数のログを同一グラフにプロットする場合にも矛盾が出ない仕様にしたいです．

**Comment by kindsenior** [comment]
個人的見解です

1は全てのグラフで統一？
2は
>横一列が同一サイズで良ければ

でいいと思っていて，
>将来的に，複数のログを同一グラフにプロットする場合にも矛盾が出ない仕様にしたいです．

に関して @rkoyama1623 のyaml様式で実現できていて？
この形式でいいんじゃないでしょうか

**Comment by rkoyama1623-jsk** [comment]
グラフのサイズは，この方向で進めるとして，すぐに実装できるかわからないので，別issue #50 を立てました．

**Comment by rkoyama1623-jsk** [comment]
目下，優先度高めのissueとして必要なのは以下３つ．

1. 文字のフォントサイズ指定(12pt)
1. 文字フォント指定 (Times ?)
1. グラフの単位を角括弧にする ( (s) -> [s] )

@Tnoriaki さん，いかがお過ごしでしょうか？

**Comment by Tnoriaki** [comment]
@rkoyama1623 さん
了解です.
３つについて調べておきます.

**Comment by rkoyama1623-jsk** [comment]
ありがとうございます！
時間の空いているときによろしくお願いします．

**Comment by Tnoriaki** [comment]
@rkoyama1623 さん
#53 
#54 
で対応いたしました.ご確認よろしくお願いいたします.

**Comment by kyawawa** [comment]
みなさんのおかげで当初の５項目は達成できました！
ありがとうございます
他に何か出てきた時のため，２月まではcloseしないでおきます

**Comment by kyawawa** [comment]
(別issueかもしれませんが)
最近次の2点ができたらと思います
1. 散布図をプロットしたい場合がある
1. xlabelの変更

どういう方針が良いものでしょうか？
それとどなたかやっていただけると非常に助かります

**Comment by rkoyama1623-jsk** [comment]
2は、 #63 で指摘があるように、
現状一番下だけ表示している仕様を維持すべきかということですね。

私は維持しなくても良いです。
後、2つの問題を別issueに分離してもらった方が良いかもしれないです。

1はやや議論の余地がありそうに思います。

**Comment by rkoyama1623-jsk** [comment]
散布図は，pyqtgraph.ScatterPlotItemに対してプロットし，
現在の使用しているpyqtgraph.PlotItemとは継承関係さえ無いので，
例えば，yamlファイルで記述するとしたら，layout.yamlに
```yaml
watt:
  type: scatter
  legends:
    - { key: watt, id: [0-5] }
```
のような書き方が可能だと思いますが，
この例のようにうっかりPlotItemを前提とした凡例を指定するとエラーになると思います．

**Comment by kyawawa** [comment]
#66 #67 に分離しました．
よろしくお願いします．

**Comment by kyawawa** [comment]
> 3. 軸の色を灰色から黒にし，補助線を点線にする

についてですが，現在のDashLineでは論文に貼った時にほぼ直線に見えてしまうかもしれません
https://github.com/kindsenior/log_plotter/blob/master/src/log_plotter/datalogger_plotter_with_pyqtgraph.py#L312

気に入らない人は以下のように自分でパターンを作ると良いかもしれません
```python
        for i, p in enumerate(self.view.ci.items.keys()):
            ax = p.getAxis('bottom')
            pen = pyqtgraph.mkPen('k', width=0.5, style=pyqtgraph.QtCore.Qt.CustomDashLine)
            pen.setDashPattern([1, 5])
            ax.setPen(pen)
            ax = p.getAxis('left')
            ax.setPen(pen)
```

**Comment by rkoyama1623-jsk** [comment]
上の修正を手が空いたときPRして良いと思います．
before
![before](https://cloud.githubusercontent.com/assets/11606776/22368721/6d7fbe70-e4cb-11e6-81d8-ab326056da29.png)
after
![after](https://cloud.githubusercontent.com/assets/11606776/22368723/712e40aa-e4cb-11e6-842d-93303702e98b.png)

**Comment by kyawawa** [comment]
問題点は通常時にグリッドが見づらくなるところですね
svgにexportするときの挙動が問題？

**Comment by kyawawa** [comment]
依然課題は多く残されている気がしますが，個別issueで対応していくということでこちらは閉じさせていただきます
