### ISSUE TITLE
pyqtgraphによるsvgのexportでフォントが埋め込まれない

### ISSUE THREAD

**Issue by rkoyama1623-jsk** [kindsenior/log_plotter#79]
Times New RomanのフォントがSVGにexportすると埋め込まれないため，エクスポートした結果のフォントが崩れる．
一応の解決策を以下にメモします．inkscapeのデフォルトフォントがTimesNewRomanで，フォントの指定がおかしいときに，デフォルトフォントを埋め込むことを利用しており，環境によってはうまく行かないかもしれません．

1. TimesNewRomanのフォントをインストールする．
```
sudo apt-get install msttcorefonts
sudo apt-get install ttf-mscorefonts-installer
```

2. inkscapeのバージョンを最新にする
```
sudo add-apt-repository ppa:inkscape.dev/stable
sudo apt-get update
sudo apt-get install inkscape
```
3. 以下のコマンドでsvgをpdfに変換する．
```
inkscape --file=xxx.svg --export-area-drawing --export-pdf=xxx.pdf
```

**Comment by kyawawa** [comment]
生成されたsvgをemacsで開いてみたら
```
font-family="&quot;Times New Roman&quot;, sans-serif"
```
みたいになっていて，ちゃんと指定は出来ているのかなぁと思いました
うまくいかなかったのはなんででしょう？
TimesNewRomanのフォントが無いＰＣで試してみたいですね

むしろ気になったのは
```
font-size="16"
```
となっていたことですが，僕だけでしょうか(これの単位がptとは限りませんが…)

**Comment by rkoyama1623-jsk** [comment]
理由はわかりませんが，inkscapeのupgradeで入ったdebパッケージのlogをメモしておきます．

```
Start-Date: 2017-01-26  21:26:38
Commandline: apt-get install inkscape
Install: python-renderpm:amd64 (3.0-1build1, automatic), python-reportlab-accel:amd64 (3.0-1build1, automatic), python-reportlab:amd64 (3.0-1build1, automatic), libpotrace0:amd64 (1.11-2, automatic), python-scour:amd64 (0.26-3build1, automatic), python-uniconvertor:amd64 (1.1.4-1ubuntu2, automatic)
Upgrade: inkscape:amd64 (0.48.4-3ubuntu2, 0.92.0+66~ubuntu14.04.1)
End-Date: 2017-01-26  21:26:49
```

**Comment by rkoyama1623-jsk** [comment]
現状の理解では以下の通りとなりました．
- pyqtgraphの出力するsvgフォントの指定はできている埋め込まれているかは不明）
- eogでsvgファイルを見るとフォントが崩れるのは，eogのバグ(firefoxやchromeではフォントが崩れない)
- 古いバージョンのinkscapeはフォントの解釈と埋め込みの能力が不十分

現象を整理すると，
pyqtgraphでsvgを出力
↓
sample.svg(eogで見るとフォントが変，firefoxで見るとフォントがTimesNewRomanで正しい)
↓
・→古いバージョンのinkscapeで変換→sample.pdf(フォントが変)
↓
・→新しいバージョンのinkscapeで変換→sample.pdf(フォントはTimesNewRomanで正しい)

TimesNewRomanのフォントがインストールされていないとどうなるかの検証は今後のTODOです．

**Comment by kyawawa** [comment]
eogや古いinkscapeが\&quot;表記に対応していない可能性があります
消すとeogでもうまく表示できました
eogのバージョンを上げると同じように解決するかも？

**Comment by kyawawa** [comment]
eogのバージョンを上げると解決するかは確認していませんが，このissueはcloseしても良いかもしれません
ちなみに僕が書いた
> font-size="16"

というのは，少し難しいのですが，基本的には16pxのことみたいです
座標変換が行われると変わってくるとか
https://triple-underscore.github.io/SVG11/coords.html#Units
(ちなみに1pt = 1.25pxだそうで，13ptに近いですね)

**Comment by rkoyama1623-jsk** [comment]
調査ありがとうございました
